server:
  port: 8888
spring:
  application.name: config-server
  profiles:
    default: composite,file
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    bus:
      enabled: true
    stream:
      default.group: "config-server.${random.uuid}"     # Each instance must have unique group

logging:
  level:
    org.springframework.cloud.config: DEBUG
